# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3be09bc6e11f5ed5ca795554e348b92415316e81b21766cd7a3da1c51124422179ad5661a171dfe90e4011ef892c94f7d49778a895efa8e4cb003eb18ba71420

test:
  secret_key_base: 14c61f0b6b8e2ee8b103c3772ab8fd3ab363b5ab5adf611c6f224d61d63d690aa000e5f305946f80b8f5be18614998cd9488e9d42fc30682768fb7c630af712d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
